/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.devlife.service.base;

import com.liferay.devlife.service.Example3Service;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.InfrastructureUtil;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the example3 remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.devlife.service.impl.Example3ServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.devlife.service.impl.Example3ServiceImpl
 * @see com.liferay.devlife.service.Example3ServiceUtil
 * @generated
 */
public abstract class Example3ServiceBaseImpl extends BaseServiceImpl
	implements Example3Service, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.devlife.service.Example3ServiceUtil} to access the example3 remote service.
	 */

	/**
	 * Returns the example1 remote service.
	 *
	 * @return the example1 remote service
	 */
	public com.liferay.devlife.service.Example1Service getExample1Service() {
		return example1Service;
	}

	/**
	 * Sets the example1 remote service.
	 *
	 * @param example1Service the example1 remote service
	 */
	public void setExample1Service(
		com.liferay.devlife.service.Example1Service example1Service) {
		this.example1Service = example1Service;
	}

	/**
	 * Returns the example2 remote service.
	 *
	 * @return the example2 remote service
	 */
	public com.liferay.devlife.service.Example2Service getExample2Service() {
		return example2Service;
	}

	/**
	 * Sets the example2 remote service.
	 *
	 * @param example2Service the example2 remote service
	 */
	public void setExample2Service(
		com.liferay.devlife.service.Example2Service example2Service) {
		this.example2Service = example2Service;
	}

	/**
	 * Returns the example3 remote service.
	 *
	 * @return the example3 remote service
	 */
	public com.liferay.devlife.service.Example3Service getExample3Service() {
		return example3Service;
	}

	/**
	 * Sets the example3 remote service.
	 *
	 * @param example3Service the example3 remote service
	 */
	public void setExample3Service(
		com.liferay.devlife.service.Example3Service example3Service) {
		this.example3Service = example3Service;
	}

	/**
	 * Returns the example4 remote service.
	 *
	 * @return the example4 remote service
	 */
	public com.liferay.devlife.service.Example4Service getExample4Service() {
		return example4Service;
	}

	/**
	 * Sets the example4 remote service.
	 *
	 * @param example4Service the example4 remote service
	 */
	public void setExample4Service(
		com.liferay.devlife.service.Example4Service example4Service) {
		this.example4Service = example4Service;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = InfrastructureUtil.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.devlife.service.Example1Service.class)
	protected com.liferay.devlife.service.Example1Service example1Service;
	@BeanReference(type = com.liferay.devlife.service.Example2Service.class)
	protected com.liferay.devlife.service.Example2Service example2Service;
	@BeanReference(type = com.liferay.devlife.service.Example3Service.class)
	protected com.liferay.devlife.service.Example3Service example3Service;
	@BeanReference(type = com.liferay.devlife.service.Example4Service.class)
	protected com.liferay.devlife.service.Example4Service example4Service;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private Example3ServiceClpInvoker _clpInvoker = new Example3ServiceClpInvoker();
}